
@base_url = http://localhost:8004/api/notes
@contact_url = http://localhost:8004/api/contact

### Get all notes 
GET {{base_url}}

### Get notes by note id
GET {{base_url}}/657bd4fc6c1950e8aa6ced5f


### Create a note

POST {{base_url}}
Content-Type: application/json

{
  "title": "How to deploy node app in pm2?",
  "text": "Deploye node app "
}

### Update a note byID

PUT  {{base_url}}/657bd4fc6c1950e8aa6ced5f
Content-Type: application/json

{
  "title": "Create a contact Manager App.V2",
  "text": "Hi Test . Email_V2"
}



### Delete note by note id
DELETE  {{base_url}}/657c11434abf20319dc5a341


### Notes Users Registration


POST http://localhost:8004/api/noteusers/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoidG9tZGVjaEBnbWFpbC5jb20iLCJpYXQiOjE3MDI4ODcyNjksImV4cCI6MTcwMjg5MDg2OX0.g4_a6seLHRMXJc7abWolyPhgC9GjoIF_7BWOlU3K1WY
Content-Type: application/json

{
  "username": "ocemguest",
  "email": "ocem.blgr20231@gmail.com",
  "password": "admin@123"
}

### Notes Users Auth

POST http://localhost:8004/api/noteusers/auth
Content-Type: application/json

{
  "username": "tomdech",
  "password": "admin@123"
}


### Contact API

POST {{contact_url}}
Content-Type: application/json

{
  "name": "Jhon Deo",
  "email": "jhon@gmail.com",
  "message":"I am intrest on DCA and PGDCA course."
}


###Get all contacts
GET  {{contact_url}}